---
title: "Erigenia analyses based on Grunwald Lab GBS tutorial"
author: "McDonnell, Moore"
date: "May 2019"
output:
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vcfR)
library(poppr)
library(hierfstat)
```

##getting the data ready
```{r read in vcf file}
setwd()
Erigenia_vcf <- read.vcfR("erigeniaC.vcf")
```


```{r population data}
setwd("~/github/Erigenia-Analyses")
pop_data <- read.table("population_data.Erigenia.txt", sep = "\t", header = TRUE)
```

```{r}
Erigenia_vcf <- read.vcfR("erigeniaC.vcf", verbose=FALSE)
```

```{r vcf to genlight}
Erigenia_genlight <- vcfR2genlight(Erigenia_vcf, ind.names)
```

```{r vcf to genind}
Erigenia_genind_pops <- vcfR2genind(Erigenia_vcf, ind.names)
```

```{r}
save(Erigenia_genlight, file="Erigenia_genlight.rdata")
```
```{r}
save(Erigenia_genind_pops, file="Erigenia_genind_pops.rdata")
```

```{r make sure data matched}
all(colnames(Erigenia_vcf@gt)[-1] == pop_data$Access.ID)
```
You want a TRUE returned. if FALSE is returned, change srr to whatever individuals are if needed, IN ORDER



```{r telling R about our data}
ploidy(Erigenia_genlight) <- 2
pop(Erigenia_genlight) <- pop_data$Locality
```
change pop to whatever populations are defined as (here, locality per .txt) I think you can also do this with individuals if you want

```{r}
ploidy(Erigenia_genind_pops) <- 2
pop(Erigenia_genind_pops) <- pop_data$Locality
```


```{r save genlight w/pops defined}
save(Erigenia_genlight, file="Erigenia_genlight.RData")
```
```{r}
save(Erigenia_genind_pops, file="Erigenia_genind_pops.RData")
```


```{r make genlight a table, takes a while}
#optional: do this to use with other programs- save the object 
Erigenia_genlight_table <-write.csv(Erigenia_genlight)
```
```{r}
Erigenia_genind_pops_table <-write.csv(Erigenia_genind_pops)
```

```{r checking the data}
Erigenia_genlight
```
```{r}
Erigenia_genind_pops
```
```{r}
Erigenia_pop<-c("PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "PB", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "YF", "SH", "SH", "SH", "SH", "SH", "SH", "SH", "SH", "SH", "SH", "MD", "MD", "MD", "MD", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "CCP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "BTP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RSSP", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "RCSPWR", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA", "SRCNA")
```

```{r turn genind to hierfstat object, add pops if needed using a vector }
Erigenia_hierfstat <- genind2hierfstat(Erigenia_genind_pops, pop= Erigenia_pop)
```
```{r, save file}
save(Erigenia_hierfstat, file="Erigenia_hierfstat.RData")
```

##Ready for analyses

```{r}
library(ape)
library(RColorBrewer)
library(ade4)
```

```{r make a genetic distance matrix}
Erigenia_genlight.dist <- dist(Erigenia_genlight)
```

```{r do same thing with poppr}
Erigenia_genlight.dist.matrix <- poppr::bitwise.dist(Erigenia_genlight)
```

```{r make genlight with pop definitions, would be good for dropping pops subsequent analyses}
Erigenia9 <- popsub(Erigenia_genlight, sublist = c("BTP", "CCP", "MD", "PB", "RCSPWR", "RSSP", "SH", "SRCNA", "YF"))
```
```{r make matrix of pop genetic distance}
Erigenia9matrix <- poppr::bitwise.dist(Erigenia9, c(Erigenia9$pop))
```
```{r calculate nei distance with population matrix}
neiErigenia9 <- nei.dist(Erigenia9matrix)
```


```{r from https://rdrr.io/cran/ade4/man/table.dist.html, graph display of ditance matrix, per pop (but we never got it to work for pops) }
table.dist(Erigenia9matrix, x=1:(attr(Erigenia9matrix, "Size")), labels = as.character(Erigenia9matrix), clabel = 1, csize = 1, grid = TRUE)
```







