---
title: "sNMF"
author: "AJM & CLM"
date: "7/1/2019"
output: html_document
---

Rmd #5

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LEA sNMF
http://membres-timc.imag.fr/Olivier.Francois/tutoRstructure.pdf
##loading the data and finding clusters
set working directory

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("LEA")
```
```{r}
library(LEA)
library(radiator)
```

put .geno from ipyrad into github folder locally, explore K's, this may take a while.

#change file name "erigeniaC_noMD.geno"
```{r sNMF pops}
erigenia_snmf_B = snmf("erigeniaC_noMD.geno", K = 1:8, CPU = 4, entropy = TRUE, project = "new", iterations = 1000, repetitions = 10)
```
#copy and paste the output from this

```{r}
project = load.snmfProject("erigeniaC_B.snmfProject")
```

```{r sNMF pops}
plot(erigenia_snmf_B, col = "blue4", cex = 1.4, pch = 19)
```

save figure
```{r making structure like plot for pub}
best2_B = which.min(cross.entropy(erigenia_snmf_B, K = 2))
my.colors <- c("tomato", "lightblue") #change colors if ya want 
pdf("B_snmf_plot_2pop.pdf", width = 6, height = 3.5)
barchart(erigenia_snmf_B, K = 2, run = best2_B,
border = NA, space = 0,
col = my.colors,
xlab = "Individuals",
ylab = "Ancestry proportions",
main = "Ancestry matrix") ->bp2_B
axis(1, at = 1:length(bp1$order),
labels = bp2_B$order, las=1,
cex.axis = .3)
dev.off()
```

```{r making structure like plot k3}
best3_B = which.min(cross.entropy(erigenia_snmf_B, K = 3))
my.colors <- c("tomato", "lightblue", "gold")
tiff(filename="B_snmf_plot_3pop.tiff", width = 4, height = 4, units = 'in', res = 300)
barchart(erigenia_snmf_B, K = 3, run = best3_B,
border = NA, space = 0,
col = my.colors,
xlab = "Individuals",
ylab = "Ancestry proportions",
main = "Ancestry matrix") ->bp3_B
axis(1, at = 1:length(bp3_B$order),
labels = bp3_B$order, las=1,
cex.axis = .3)
dev.off()
```


#don't really need below but left it 
not sure what this is, but may be good:
```{r p values}
# Population differentiation tests
p = snmf.pvalues(erigenia_snmf_B,
entropy = TRUE,
ploidy = 2,
K = 2)
pvalues = p$pvalues
par(mfrow = c(2,1))
hist(pvalues, col = "orange")
plot(-log10(pvalues), pch = 19, col = "blue", cex = .7)
```

lfmm quasi gwas 
```{r adjusted p}
# compute adjusted p-values
p = lfmm.pvalues(erigenia_snmf_B, K = 2)
pvalues = p$pvalues
# GWAS significance test
par(mfrow = c(2,1))
hist(pvalues, col = "lightblue")
plot(-log10(pvalues), pch = 19, col = "blue", cex = .7)
```

