---
title: "Erigenia_GeneticDiversity"
author: "AJM & CLM"
date: "5/15/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("adegenet") #For storing genotype data
library(hierfstat) #For calculating pairwise Fst
library(ggplot2) #For plotting
library(reshape2) #For plotting
library(plyr)
library("cowplot") #For plotting manuscript figs
library(readr)
```


```{r}
radiator_genlight_a_noMD <- read_rds("/Volumes/Thunderbolt/Users/PostDoc/Github/Erigenia-Analyses/a166_radiator_genomic_converter_20190513a1509/radiator_genlight_20190513a1614.RData")
```
```{r}
radiator_hf_a_noMD <- read.fstat("/Volumes/Thunderbolt/Users/PostDoc/Github/Erigenia-Analyses/a166_radiator_genomic_converter_20190513a1509/radiator_data_20190513a1509.dat", na.s = c("0","00","000","0000","00000","000000","NA"))
```

```{r}
basicstat <- basic.stats(radiator_hf_a_noMD, diploid=TRUE, digits=3)
```
```{r}
save(basicstat, file="basicstat.RData")

```

```{r}
names(basicstat)
```
```{r}
overall_basic_stats <- as.data.frame(basicstat$overall)
overall_basic_stats
```

get bootstrap confidence values for Fis
```{r}
boot<- boot.ppfis(radiator_hf_a_noMD, nboot=1000)
boot5<-boot.ppfis(radiator_hf_a_noMD, nboot=1000, quant=0.5)
```
this takes a while (about 1 hour)

```{r}
boot
boot5
```


```{r}
colnames(basicstat$Ho) <- pop_order_noMD
Ho <- colMeans(basicstat$Ho,na.rm=T)
He <- colMeans(basicstat$Hs,na.rm=T)
Fis <- boot5$fis.ci$ll
popgen_stats_noMD <- cbind(Ho,He,Fis,boot$fis.ci)
popgen_stats_noMD
```

```{r}
popgen_stats_noMD.csv <-write.table(popgen_stats_noMD, sep=",", dec=".", row.names=TRUE, col.names=TRUE)

save(popgen_stats_noMD, file="popgen_stats_noMD")
```



PCA with hierfstat

```{r}
pca<- indpca(radiator_hf_a_noMD, ind.labels=radiator_hf_a_noMD[,1])
```
```{r}
plot(pca, col=radiator_hf_a_noMD[,1], cex=1.0)
```
hard to see but PB, SH, and YF are the upper three pops. Crazy separation!

PCA with something else.. glPCA id what I've used.. can send code to modify



use radiator_genlight_a_noMD to make a PCA
```{r} 
erigenia.pca <- glPca(radiator_genlight_a_noMD, nf = 3)
barplot(100*erigenia.pca$eig/sum(erigenia.pca$eig), col = heat.colors(50), main="PCA Eigenvalues")
title(ylab="Percent of variance\nexplained", line = 2)
title(xlab="Eigenvalues", line = 1)
```


```{r saving glPCA}
save(erigenia.pca, file= "erigenia.pca.RData")
```

```{r glPCA with ggplot}
erigenia.pca.scores <- as.data.frame(erigenia.pca$scores)
erigenia.pca.scores$pop <- pop(radiator_genlight_a_noMD)
```
```{r}
myCol <- c("brown","purple","green","orange","red","blue","black","yellow")
```


```{r}
set.seed(17)
p_1_2 <- ggplot(erigenia.pca.scores, aes(x=PC1, y=PC2, colour=pop)) 
p_1_2  <- p_1_2  + geom_point(size=2)
#p_1_2  <- p_1_2  + stat_ellipse(level = 0.95, size = 1) -this doesn't work with theses points, but could be used for better clustering 
p_1_2  <- p_1_2  + scale_color_manual(values = myCol) 
p_1_2  <- p_1_2  + geom_hline(yintercept = 0) 
p_1_2  <- p_1_2  + geom_vline(xintercept = 0) 
p_1_2  <- p_1_2  + theme_bw()

p_1_2
```

```{r other PCs in ggplot}
set.seed(17)
p_2_3 <- ggplot(erigenia.pca.scores, aes(x=PC2, y=PC3, colour=pop)) 
p_2_3 <- p_2_3 + geom_point(size=2)
#p_2_3 <- p_2_3 + stat_ellipse(level = 0.95, size = 1)
p_2_3 <- p_2_3 + scale_color_manual(values = myCol) 
p_2_3 <- p_2_3 + geom_hline(yintercept = 0) 
p_2_3 <- p_2_3 + geom_vline(xintercept = 0) 
p_2_3 <- p_2_3 + theme_bw()

p_2_3
```


```{r other PCs in ggplot 2}
set.seed(17)
p_1_3 <- ggplot(erigenia.pca.scores, aes(x=PC1, y=PC3, colour=pop)) 
p_1_3 <- p_2_3 + geom_point(size=2)
#p_1_3 <- p_1_3 + stat_ellipse(level = 0.95, size = 1)
p_1_3 <- p_1_3 + scale_color_manual(values = myCol) 
p_1_3 <- p_1_3 + geom_hline(yintercept = 0) 
p_1_3 <- p_1_3 + geom_vline(xintercept = 0) 
p_1_3 <- p_1_3 + theme_bw()

p_1_3
```


save fig 
```{r}
save_plot("Erigenia_PCA_PC1_2.pdf", plot = p_1_2, ncol = 1, nrow = 1, base_height = 9, base_aspect_ratio = 1.1, base_width = NULL, cols = NULL,rows = NULL, dpi = 600)

save_plot("Erigenia_PCA_PC1_3.pdf", plot = p_1_3, ncol = 1, nrow = 1, base_height = 9, base_aspect_ratio = 1.1, base_width = NULL, cols = NULL,rows = NULL, dpi = 600)
```

