---
title: "Erigenia sNMF"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LEA sNMF
http://membres-timc.imag.fr/Olivier.Francois/tutoRstructure.pdf
##loading the data and finding clusters
set working directory

```{r sNMF pops}
erigenia_snmf = snmf("erigeniaC.geno", K = 1:15, ploidy = 2, entropy = T, CPU = 1, project = "new")
plot(erigenia_snmf, col = "blue4", cex = 1.4, pch = 19)
```
Change K, ploidy (if needed), and CPUs if desired
took ~3 hours

run with defaults for seed, error tolerance etc for first go through
started with 1:15 (number of sites) - no leveling off, changed to 1:44


```{r save sNMF}
save(erigenia_snmf, file ="erigenia_snmf.RData")
```
above didn't work but shouldn't need with below command
```{r}
 project = load.snmfProject("s_viburnum1.snmfProject")
```


```{r makinf structure like plot}
best = which.min(cross.entropy(erigenia_snmf, K = 5))
my.colors <- c("tomato", "lightblue",
"olivedrab", "gold", "cyan")
bp1 <- barchart(s_viburnum, K = 5, run = best,
border = NA, space = 0,
col = my.colors,
xlab = "Individuals",
ylab = "Ancestry proportions",
main = "Ancestry matrix") 
axis(1, at = 1:length(bp$order),
labels = bp$order, las=1,
cex.axis = .3)
```
https://rdrr.io/bioc/LEA/man/barchart.html
change K and add colors if needed


```{r p values}
# Population differentiation tests
p = snmf.pvalues(erigenia_snmf,
entropy = TRUE,
ploidy = 2,
K = 5)
pvalues = p$pvalues
par(mfrow = c(2,1))
hist(pvalues, col = "orange")
plot(-log10(pvalues), pch = 19, col = "blue", cex = .7)
```


```{r adjusted p}
# compute adjusted p-values
p = lfmm.pvalues(erigenia_snmf, K = 5)
pvalues = p$pvalues
# GWAS significance test
par(mfrow = c(2,1))
hist(pvalues, col = "lightblue")
plot(-log10(pvalues), pch = 19, col = "blue", cex = .7)
```